In [1]:
import torch
from torch.autograd import Variable

In [2]:
pwd

'C:\\AAA721\\d2l-pytorch\\Ch04_The_Preliminaries_A_Crashcourse'

In [3]:
import sys
sys.path

['C:\\AAA721\\envs\\venv\\python36.zip',
 'C:\\AAA721\\envs\\venv\\DLLs',
 'C:\\AAA721\\envs\\venv\\lib',
 'C:\\AAA721\\envs\\venv',
 '',
 'C:\\AAA721\\envs\\venv\\lib\\site-packages',
 'C:\\AAA721\\envs\\venv\\lib\\site-packages\\win32',
 'C:\\AAA721\\envs\\venv\\lib\\site-packages\\win32\\lib',
 'C:\\AAA721\\envs\\venv\\lib\\site-packages\\Pythonwin',
 'C:\\AAA721\\envs\\venv\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Hodong Kim\\.ipython']

In [4]:
x = Variable(torch.arange(4, dtype=torch.float32).reshape((4, 1)), requires_grad=True)
print(x)

tensor([[0.],
        [1.],
        [2.],
        [3.]], requires_grad=True)


In [5]:
y = 2*torch.mm(x.t(),x)
print(y)

tensor([[28.]], grad_fn=<MulBackward0>)


In [6]:
y.backward()

In [7]:
print("x.grad:", x.grad)
print("x.grad_fn:", x.grad_fn)
print("y.grad_fn:", y.grad_fn)

x.grad: tensor([[ 0.],
        [ 4.],
        [ 8.],
        [12.]])
x.grad_fn: None
y.grad_fn: <MulBackward0 object at 0x00000265DA8B1160>


In [8]:
print((x.grad - 4*x).norm().item() == 0)
print(x.grad)

True
tensor([[ 0.],
        [ 4.],
        [ 8.],
        [12.]])


In [9]:
def f(a):
    b = a * 2
    while b.norm().item() < 1000:
        b = b * 2
    if b.sum().item() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [10]:
a = torch.randn(size=(1,))
a.requires_grad=True
d = f(a)
d.backward()

In [11]:
print(a.grad == (d / a))

tensor([True])


In [12]:
x = Variable(torch.tensor([[0.],[1.],[2.],[3.]]), requires_grad=True)
y = x * 2
z = y * x

head_gradient = torch.tensor([[10], [1.], [.1], [.01]])
z.backward(head_gradient)
print(x.grad)

tensor([[0.0000],
        [4.0000],
        [0.8000],
        [0.1200]])
